-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id serial NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.authtoken_token
(
    key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
    CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_amdconf
(
    id serial NOT NULL,
    initial_silence integer NOT NULL,
    greeting integer NOT NULL,
    after_greeting_silence integer NOT NULL,
    total_analysis_time integer NOT NULL,
    min_word_length integer NOT NULL,
    between_words_silence integer NOT NULL,
    maximum_number_of_words integer NOT NULL,
    maximum_word_length integer NOT NULL,
    silence_threshold integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_amdconf_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_audiosasteriskconf
(
    id serial NOT NULL,
    paquete_idioma character varying(2) COLLATE pg_catalog."default" NOT NULL,
    esta_instalado boolean NOT NULL,
    CONSTRAINT configuracion_telefonia_app_audiosasteriskconf_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_destinoentrante
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    tipo integer NOT NULL,
    object_id integer NOT NULL,
    content_type_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_destinoentrante_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia__tipo_object_id_04593ce3_uniq UNIQUE (tipo, object_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_destinopersonalizado
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    custom_destination character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT configuracion_telefonia_app_destinopersonalizado_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_destinoperso_custom_destination_key UNIQUE (custom_destination),
    CONSTRAINT configuracion_telefonia_app_destinopersonalizado_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_esquemagrabaciones
(
    id serial NOT NULL,
    id_contacto boolean NOT NULL,
    fecha boolean NOT NULL,
    telefono_contacto boolean NOT NULL,
    id_campana boolean NOT NULL,
    id_externo_contacto boolean NOT NULL,
    id_externo_campana boolean NOT NULL,
    id_agente boolean NOT NULL,
    CONSTRAINT configuracion_telefonia_app_esquemagrabaciones_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_grupohorario
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT configuracion_telefonia_app_grupohorario_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_grupohorario_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_hangup
(
    id serial NOT NULL,
    CONSTRAINT configuracion_telefonia_app_hangup_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_identificadorcliente
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tipo_interaccion integer NOT NULL,
    url character varying(128) COLLATE pg_catalog."default",
    longitud_id_esperado integer,
    timeout integer NOT NULL,
    intentos integer NOT NULL,
    audio_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_identificadorcliente_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_identificadorcliente_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_ivr
(
    id serial NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    time_out integer NOT NULL,
    time_out_retries integer NOT NULL,
    invalid_retries integer NOT NULL,
    audio_principal_id integer NOT NULL,
    invalid_audio_id integer,
    time_out_audio_id integer,
    CONSTRAINT configuracion_telefonia_app_ivr_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_ivr_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_musicadeespera
(
    id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    audio_original character varying(100) COLLATE pg_catalog."default",
    audio_asterisk character varying(100) COLLATE pg_catalog."default",
    playlist_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_musicadeespera_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_musicadeespera_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_opciondestino
(
    id serial NOT NULL,
    valor character varying(30) COLLATE pg_catalog."default" NOT NULL,
    destino_anterior_id integer NOT NULL,
    destino_siguiente_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_opciondestino_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia__destino_anterior_id_valo_78f24331_uniq UNIQUE (destino_anterior_id, valor)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_ordentroncal
(
    id serial NOT NULL,
    orden integer NOT NULL,
    ruta_saliente_id integer NOT NULL,
    troncal_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_ordentroncal_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia__orden_ruta_saliente_id_e5100a3b_uniq UNIQUE (orden, ruta_saliente_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_patrondediscado
(
    id serial NOT NULL,
    prepend character varying(32) COLLATE pg_catalog."default",
    prefix character varying(32) COLLATE pg_catalog."default",
    match_pattern character varying(100) COLLATE pg_catalog."default" NOT NULL,
    orden integer NOT NULL,
    ruta_saliente_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_patrondediscado_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia__orden_ruta_saliente_id_991d147d_uniq UNIQUE (orden, ruta_saliente_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_playlist
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT configuracion_telefonia_app_playlist_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_playlist_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_rutaentrante
(
    id serial NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(30) COLLATE pg_catalog."default" NOT NULL,
    prefijo_caller_id character varying(30) COLLATE pg_catalog."default",
    idioma integer NOT NULL,
    destino_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_rutaentrante_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_rutaentrante_nombre_key UNIQUE (nombre),
    CONSTRAINT configuracion_telefonia_app_rutaentrante_telefono_key UNIQUE (telefono)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_rutasaliente
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    ring_time integer NOT NULL,
    dial_options character varying(512) COLLATE pg_catalog."default" NOT NULL,
    orden integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_rutasaliente_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_rutasaliente_nombre_key UNIQUE (nombre),
    CONSTRAINT configuracion_telefonia_app_rutasaliente_orden_d65178fe_uniq UNIQUE (orden)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_troncalsip
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    canales_maximos integer NOT NULL,
    caller_id character varying(100) COLLATE pg_catalog."default",
    register_string character varying(100) COLLATE pg_catalog."default",
    text_config text COLLATE pg_catalog."default" NOT NULL,
    tecnologia integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_troncalsip_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_troncalsip_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_validacionfechahora
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    grupo_horario_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_validacionfechahora_pkey PRIMARY KEY (id),
    CONSTRAINT configuracion_telefonia_app_validacionfechahora_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.configuracion_telefonia_app_validaciontiempo
(
    id serial NOT NULL,
    tiempo_inicial time without time zone NOT NULL,
    tiempo_final time without time zone NOT NULL,
    dia_semana_inicial integer,
    dia_semana_final integer,
    dia_mes_inicio integer,
    dia_mes_final integer,
    mes_inicio integer,
    mes_final integer,
    grupo_horario_id integer NOT NULL,
    CONSTRAINT configuracion_telefonia_app_validaciontiempo_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.constance_config
(
    id serial NOT NULL,
    key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    CONSTRAINT constance_config_pkey PRIMARY KEY (id),
    CONSTRAINT constance_config_key_key UNIQUE (key)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.defender_accessattempt
(
    id serial NOT NULL,
    user_agent character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ip_address inet,
    username character varying(255) COLLATE pg_catalog."default",
    http_accept character varying(1025) COLLATE pg_catalog."default" NOT NULL,
    path_info character varying(255) COLLATE pg_catalog."default" NOT NULL,
    attempt_time timestamp with time zone NOT NULL,
    login_valid boolean NOT NULL,
    CONSTRAINT defender_accessattempt_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id serial NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id serial NOT NULL,
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id serial NOT NULL,
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.easyaudit_crudevent
(
    id serial NOT NULL,
    event_type smallint NOT NULL,
    object_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    object_repr text COLLATE pg_catalog."default",
    object_json_repr text COLLATE pg_catalog."default",
    datetime timestamp with time zone NOT NULL,
    content_type_id integer NOT NULL,
    user_id integer,
    user_pk_as_string character varying(255) COLLATE pg_catalog."default",
    changed_fields text COLLATE pg_catalog."default",
    CONSTRAINT easyaudit_crudevent_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.easyaudit_loginevent
(
    id serial NOT NULL,
    login_type smallint NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    datetime timestamp with time zone NOT NULL,
    user_id integer,
    remote_ip character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT easyaudit_loginevent_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.easyaudit_requestevent
(
    id serial NOT NULL,
    url character varying(254) COLLATE pg_catalog."default" NOT NULL,
    method character varying(20) COLLATE pg_catalog."default" NOT NULL,
    query_string text COLLATE pg_catalog."default",
    remote_ip character varying(50) COLLATE pg_catalog."default",
    datetime timestamp with time zone NOT NULL,
    user_id integer,
    CONSTRAINT easyaudit_requestevent_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.form_app_ciudadmunicipio
(
    id serial NOT NULL,
    nombre character varying(600) COLLATE pg_catalog."default" NOT NULL,
    activo integer NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT form_app_ciudadmunicipio_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.form_app_gestion
(
    id serial NOT NULL,
    nombre_completo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_identificacion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    numero_documento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(600) COLLATE pg_catalog."default",
    observaciones text COLLATE pg_catalog."default",
    telefono_llamada character varying(20) COLLATE pg_catalog."default" NOT NULL,
    call_id character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    agente_id integer,
    campana_id integer,
    ciudad_municipio_id integer,
    telefono character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT form_app_gestion_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_actuacionvigente
(
    id serial NOT NULL,
    domingo boolean NOT NULL,
    lunes boolean NOT NULL,
    martes boolean NOT NULL,
    miercoles boolean NOT NULL,
    jueves boolean NOT NULL,
    viernes boolean NOT NULL,
    sabado boolean NOT NULL,
    hora_desde time without time zone NOT NULL,
    hora_hasta time without time zone NOT NULL,
    campana_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_actuacionvigente_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_actuacionvigente_campana_id_key UNIQUE (campana_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_agendacontacto
(
    id serial NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    tipo_agenda integer NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    agente_id integer NOT NULL,
    campana_id integer,
    contacto_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_agendacontacto_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_agenteencontacto
(
    id serial NOT NULL,
    agente_id integer NOT NULL,
    contacto_id integer NOT NULL,
    datos_contacto text COLLATE pg_catalog."default" NOT NULL,
    telefono_contacto character varying(128) COLLATE pg_catalog."default" NOT NULL,
    campana_id integer NOT NULL,
    estado integer NOT NULL,
    modificado timestamp with time zone,
    es_originario boolean NOT NULL,
    orden integer NOT NULL,
    CONSTRAINT ominicontacto_app_agenteencontacto_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_agenteensistemaexterno
(
    id serial NOT NULL,
    id_externo_agente character varying(128) COLLATE pg_catalog."default" NOT NULL,
    agente_id integer NOT NULL,
    sistema_externo_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_agenteensistemaexterno_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_agente_sistema_externo_id_agent_90630bef_uniq UNIQUE (sistema_externo_id, agente_id),
    CONSTRAINT ominicontacto_app_agente_sistema_externo_id_id_ex_866c1341_uniq UNIQUE (sistema_externo_id, id_externo_agente)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_agenteprofile
(
    id serial NOT NULL,
    sip_extension integer NOT NULL,
    sip_password character varying(128) COLLATE pg_catalog."default",
    estado integer NOT NULL,
    is_inactive boolean NOT NULL,
    borrado boolean NOT NULL,
    grupo_id integer NOT NULL,
    reported_by_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_agenteprofile_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_agenteprofile_sip_extension_key UNIQUE (sip_extension),
    CONSTRAINT ominicontacto_app_agenteprofile_user_id_key UNIQUE (user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_archivodeaudio
(
    id serial NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    audio_original character varying(100) COLLATE pg_catalog."default",
    audio_asterisk character varying(100) COLLATE pg_catalog."default",
    borrado boolean NOT NULL,
    CONSTRAINT ominicontacto_app_archivodeaudio_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_archivodeaudio_descripcion_key UNIQUE (descripcion)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_auditoriacalificacion
(
    id serial NOT NULL,
    resultado integer NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    calificacion_id integer NOT NULL,
    revisada boolean NOT NULL,
    CONSTRAINT ominicontacto_app_auditoriacalificacion_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_auditoriacalificacion_calificacion_id_key UNIQUE (calificacion_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_autenticacionsitioexterno
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    url character varying(250) COLLATE pg_catalog."default" NOT NULL,
    username character varying(128) COLLATE pg_catalog."default" NOT NULL,
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    campo_token character varying(128) COLLATE pg_catalog."default" NOT NULL,
    duracion integer NOT NULL,
    campo_duracion character varying(128) COLLATE pg_catalog."default" NOT NULL,
    ssl_estricto boolean NOT NULL,
    token text COLLATE pg_catalog."default",
    expiracion_token timestamp with time zone,
    CONSTRAINT ominicontacto_app_autenticacionsitioexterno_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_autenticacionsitioexterno_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_basedatoscontacto
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta timestamp with time zone NOT NULL,
    archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    nombre_archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    metadata text COLLATE pg_catalog."default",
    sin_definir boolean NOT NULL,
    cantidad_contactos integer NOT NULL,
    estado integer NOT NULL,
    oculto boolean NOT NULL,
    CONSTRAINT ominicontacto_app_basedatoscontacto_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_basedatoscontacto_nombre_6cf964df_uniq UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_blacklist
(
    id integer NOT NULL DEFAULT nextval('ominicontacto_app_backlist_id_seq'::regclass),
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta timestamp with time zone NOT NULL,
    archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    nombre_archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    sin_definir boolean NOT NULL,
    cantidad_contactos integer NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    CONSTRAINT ominicontacto_app_backlist_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_calificacioncliente
(
    id serial NOT NULL,
    fecha timestamp with time zone NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    agendado boolean NOT NULL,
    es_calificacion_manual boolean NOT NULL,
    agente_id integer NOT NULL,
    contacto_id integer NOT NULL,
    opcion_calificacion_id integer NOT NULL,
    callid character varying(32) COLLATE pg_catalog."default",
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    tipo_agenda integer,
    CONSTRAINT ominicontacto_app_calificacioncliente_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_campana
(
    id serial NOT NULL,
    estado integer NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    fecha_inicio date,
    fecha_fin date,
    oculto boolean NOT NULL,
    campaign_id_wombat integer,
    type integer NOT NULL,
    tipo_interaccion integer NOT NULL,
    es_template boolean NOT NULL,
    nombre_template character varying(128) COLLATE pg_catalog."default",
    es_manual boolean NOT NULL,
    objetivo integer NOT NULL,
    tiempo_desconexion integer NOT NULL,
    bd_contacto_id integer,
    reported_by_id integer NOT NULL,
    sitio_externo_id integer,
    mostrar_nombre boolean NOT NULL,
    id_externo character varying(128) COLLATE pg_catalog."default",
    sistema_externo_id integer,
    campo_desactivacion character varying(128) COLLATE pg_catalog."default",
    campos_bd_no_editables character varying(2052) COLLATE pg_catalog."default" NOT NULL,
    campos_bd_ocultos character varying(2052) COLLATE pg_catalog."default" NOT NULL,
    outcid character varying(128) COLLATE pg_catalog."default",
    outr_id integer,
    videocall_habilitada boolean NOT NULL,
    speech text COLLATE pg_catalog."default",
    campo_direccion character varying(128) COLLATE pg_catalog."default",
    mostrar_did boolean NOT NULL,
    mostrar_nombre_ruta_entrante boolean NOT NULL,
    control_de_duplicados integer NOT NULL,
    prioridad integer NOT NULL,
    campos_bd_obligatorios character varying(2052) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ominicontacto_app_campana_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_campana_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_campana_supervisors
(
    id serial NOT NULL,
    campana_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_campana_supervisors_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_campan_campana_id_user_id_abb0a2c5_uniq UNIQUE (campana_id, user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_chat
(
    id serial NOT NULL,
    fecha_hora_chat timestamp with time zone NOT NULL,
    agente_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_chat_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_clientewebphoneprofile
(
    id serial NOT NULL,
    sip_extension integer NOT NULL,
    is_inactive boolean NOT NULL,
    borrado boolean NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_clientewebphoneprofile_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_clientewebphoneprofile_sip_extension_key UNIQUE (sip_extension),
    CONSTRAINT ominicontacto_app_clientewebphoneprofile_user_id_key UNIQUE (user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_configuraciondeagentesdecampana
(
    id serial NOT NULL,
    set_auto_attend_inbound boolean NOT NULL,
    auto_attend_inbound boolean NOT NULL,
    set_auto_attend_dialer boolean NOT NULL,
    auto_attend_dialer boolean NOT NULL,
    set_auto_unpause boolean NOT NULL,
    auto_unpause integer NOT NULL,
    set_obligar_calificacion boolean NOT NULL,
    obligar_calificacion boolean NOT NULL,
    campana_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_configuraciondeagentesdecampana_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_configuraciondeagentesdecampan_campana_id_key UNIQUE (campana_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_configuraciondepausa
(
    id serial NOT NULL,
    time_to_end_pause integer NOT NULL,
    conjunto_de_pausa_id integer NOT NULL,
    pausa_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_configuraciondepausa_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_conjuntodepausa
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ominicontacto_app_conjuntodepausa_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_contacto
(
    id serial NOT NULL,
    telefono character varying(128) COLLATE pg_catalog."default" NOT NULL,
    datos text COLLATE pg_catalog."default" NOT NULL,
    bd_contacto_id integer,
    es_originario boolean NOT NULL,
    id_externo character varying(128) COLLATE pg_catalog."default",
    CONSTRAINT ominicontacto_app_contacto_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_contactoblacklist
(
    id serial NOT NULL,
    telefono character varying(128) COLLATE pg_catalog."default" NOT NULL,
    black_list_id integer,
    CONSTRAINT ominicontacto_app_contactoblacklist_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_contactoblacklist_telefono_a1dfe877_uniq UNIQUE (telefono)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_contactolistarapida
(
    id serial NOT NULL,
    telefono character varying(128) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    lista_rapida_id integer,
    CONSTRAINT ominicontacto_app_contactolistarapida_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_fieldformulario
(
    id serial NOT NULL,
    nombre_campo character varying(64) COLLATE pg_catalog."default" NOT NULL,
    orden integer NOT NULL,
    tipo integer NOT NULL,
    values_select text COLLATE pg_catalog."default",
    is_required boolean NOT NULL,
    formulario_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_fieldformulario_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_fieldf_orden_formulario_id_6218007e_uniq UNIQUE (orden, formulario_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_formulario
(
    id serial NOT NULL,
    nombre character varying(64) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    oculto boolean NOT NULL,
    CONSTRAINT ominicontacto_app_formulario_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_grabacion_marca
(
    id serial NOT NULL,
    callid character varying(45) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ominicontacto_app_grabacion_marca_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_grupo
(
    id serial NOT NULL,
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    auto_attend_inbound boolean NOT NULL,
    auto_attend_dialer boolean NOT NULL,
    auto_unpause integer NOT NULL,
    obligar_calificacion boolean NOT NULL,
    call_off_camp boolean NOT NULL,
    acceso_grabaciones_agente boolean NOT NULL,
    acceso_dashboard_agente boolean NOT NULL,
    on_hold boolean NOT NULL,
    cantidad_agendas_personales integer,
    limitar_agendas_personales boolean NOT NULL,
    limitar_agendas_personales_en_dias boolean NOT NULL,
    tiempo_maximo_para_agendar integer,
    obligar_despausa boolean NOT NULL,
    show_console_timers boolean NOT NULL,
    acceso_agendas_agente boolean NOT NULL,
    acceso_calificaciones_agente boolean NOT NULL,
    acceso_campanas_preview_agente boolean NOT NULL,
    acceso_contactos_agente boolean NOT NULL,
    conjunto_de_pausa_id integer,
    CONSTRAINT ominicontacto_app_grupo_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_grupo_nombre_09c6de5a_uniq UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_historicalcalificacioncliente
(
    id integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    agendado boolean NOT NULL,
    es_calificacion_manual boolean NOT NULL,
    history_id serial NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100) COLLATE pg_catalog."default",
    history_type character varying(1) COLLATE pg_catalog."default" NOT NULL,
    agente_id integer,
    contacto_id integer,
    history_user_id integer,
    opcion_calificacion_id integer,
    callid character varying(32) COLLATE pg_catalog."default",
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    tipo_agenda integer,
    CONSTRAINT ominicontacto_app_historicalcalificacioncliente_pkey PRIMARY KEY (history_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_historicalrespuestaformulariogestion
(
    id integer NOT NULL,
    metadata text COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp with time zone NOT NULL,
    history_id serial NOT NULL,
    history_date timestamp with time zone NOT NULL,
    history_change_reason character varying(100) COLLATE pg_catalog."default",
    history_type character varying(1) COLLATE pg_catalog."default" NOT NULL,
    calificacion_id integer,
    history_user_id integer,
    CONSTRAINT ominicontacto_app_historicalrespuestaformulariogestion_pkey PRIMARY KEY (history_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_listasrapidas
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    fecha_alta timestamp with time zone NOT NULL,
    archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    nombre_archivo_importacion character varying(256) COLLATE pg_catalog."default" NOT NULL,
    cantidad_contactos integer NOT NULL,
    metadata text COLLATE pg_catalog."default",
    CONSTRAINT ominicontacto_app_listasrapidas_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_listasrapidas_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_mensajechat
(
    id serial NOT NULL,
    mensaje text COLLATE pg_catalog."default" NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    chat_id integer NOT NULL,
    sender_id integer NOT NULL,
    to_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_mensajechat_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_nombrecalificacion
(
    id serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ominicontacto_app_nombrecalificacion_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_opcioncalificacion
(
    id serial NOT NULL,
    tipo integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    campana_id integer NOT NULL,
    formulario_id integer,
    oculta boolean NOT NULL,
    positiva boolean NOT NULL,
    interaccion_crm boolean NOT NULL,
    CONSTRAINT ominicontacto_app_opcioncalificacion_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_parametroscrm
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    valor character varying(256) COLLATE pg_catalog."default" NOT NULL,
    tipo integer NOT NULL,
    campana_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_parametroscrm_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_pausa
(
    id serial NOT NULL,
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    tipo character varying(1) COLLATE pg_catalog."default" NOT NULL,
    eliminada boolean NOT NULL,
    CONSTRAINT ominicontacto_app_pausa_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_pausa_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_reglaincidenciaporcalificacion
(
    id serial NOT NULL,
    intento_max integer NOT NULL,
    reintentar_tarde integer NOT NULL,
    en_modo integer NOT NULL,
    opcion_calificacion_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_reglaincidenciaporcalificacion_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_reglaincidenciapor_opcion_calificacion_id_key UNIQUE (opcion_calificacion_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_reglasincidencia
(
    id serial NOT NULL,
    estado integer NOT NULL,
    estado_personalizado character varying(128) COLLATE pg_catalog."default",
    intento_max integer NOT NULL,
    reintentar_tarde integer NOT NULL,
    en_modo integer NOT NULL,
    campana_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_reglasincidencia_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_respuestaformulariogestion
(
    id integer NOT NULL DEFAULT nextval('ominicontacto_app_metadatacliente_id_seq'::regclass),
    metadata text COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp with time zone NOT NULL,
    calificacion_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_metadatacliente_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_sistemaexterno
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ominicontacto_app_sistemaexterno_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_sistemaexterno_nombre_key UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_sitioexterno
(
    id serial NOT NULL,
    nombre character varying(128) COLLATE pg_catalog."default" NOT NULL,
    url character varying(250) COLLATE pg_catalog."default" NOT NULL,
    oculto boolean NOT NULL,
    metodo integer NOT NULL,
    disparador integer NOT NULL,
    formato integer,
    objetivo integer,
    autenticacion_id integer,
    CONSTRAINT ominicontacto_app_sitioexterno_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_sitioexterno_nombre_f6a98fa8_uniq UNIQUE (nombre)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_supervisorprofile
(
    id serial NOT NULL,
    sip_extension integer NOT NULL,
    sip_password character varying(128) COLLATE pg_catalog."default",
    is_administrador boolean NOT NULL,
    is_customer boolean NOT NULL,
    borrado boolean NOT NULL,
    "timestamp" character varying(64) COLLATE pg_catalog."default",
    user_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_supervisorprofile_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_supervisorprofile_sip_extension_key UNIQUE (sip_extension),
    CONSTRAINT ominicontacto_app_supervisorprofile_user_id_key UNIQUE (user_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_user
(
    id serial NOT NULL,
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(30) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    is_agente boolean NOT NULL,
    is_supervisor boolean NOT NULL,
    last_session_key character varying(40) COLLATE pg_catalog."default",
    borrado boolean NOT NULL,
    is_cliente_webphone boolean NOT NULL,
    CONSTRAINT ominicontacto_app_user_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_user_username_key UNIQUE (username)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_user_groups
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_user_groups_user_id_group_id_9ea58fa3_uniq UNIQUE (user_id, group_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.ominicontacto_app_user_user_permissions
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT ominicontacto_app_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT ominicontacto_app_user_u_user_id_permission_id_c7a8cf96_uniq UNIQUE (user_id, permission_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.queue_log
(
    id serial NOT NULL,
    "time" character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    callid character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    queuename character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    agent character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    event character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    data1 character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    data2 character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    data3 character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    data4 character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    data5 character varying(100) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT queue_log_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.queue_member_table
(
    id serial NOT NULL,
    membername character varying(128) COLLATE pg_catalog."default" NOT NULL,
    interface character varying(128) COLLATE pg_catalog."default" NOT NULL,
    penalty integer NOT NULL,
    paused integer NOT NULL,
    id_campana character varying(128) COLLATE pg_catalog."default" NOT NULL,
    member_id integer NOT NULL,
    queue_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT queue_member_table_pkey PRIMARY KEY (id),
    CONSTRAINT queue_member_table_queue_name_member_id_1e319083_uniq UNIQUE (queue_name, member_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.queue_table
(
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    timeout bigint,
    retry bigint,
    maxlen bigint NOT NULL,
    wrapuptime bigint NOT NULL,
    servicelevel bigint NOT NULL,
    strategy character varying(128) COLLATE pg_catalog."default" NOT NULL,
    eventmemberstatus boolean NOT NULL,
    eventwhencalled boolean NOT NULL,
    weight bigint NOT NULL,
    ringinuse boolean NOT NULL,
    setinterfacevar boolean NOT NULL,
    wait integer NOT NULL,
    auto_grabacion boolean NOT NULL,
    detectar_contestadores boolean NOT NULL,
    ep_id_wombat integer,
    announce character varying(128) COLLATE pg_catalog."default",
    announce_frequency bigint,
    initial_predictive_model boolean NOT NULL,
    initial_boost_factor numeric(3, 1),
    musiconhold_id integer,
    context character varying(128) COLLATE pg_catalog."default",
    monitor_join boolean,
    monitor_format character varying(128) COLLATE pg_catalog."default",
    queue_youarenext character varying(128) COLLATE pg_catalog."default",
    queue_thereare character varying(128) COLLATE pg_catalog."default",
    queue_callswaiting character varying(128) COLLATE pg_catalog."default",
    queue_holdtime character varying(128) COLLATE pg_catalog."default",
    queue_minutes character varying(128) COLLATE pg_catalog."default",
    queue_seconds character varying(128) COLLATE pg_catalog."default",
    queue_lessthan character varying(128) COLLATE pg_catalog."default",
    queue_thankyou character varying(128) COLLATE pg_catalog."default",
    queue_reporthold character varying(128) COLLATE pg_catalog."default",
    announce_round_seconds bigint,
    announce_holdtime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    joinempty character varying(128) COLLATE pg_catalog."default",
    leavewhenempty character varying(128) COLLATE pg_catalog."default",
    reportholdtime boolean,
    memberdelay bigint,
    timeoutrestart boolean,
    audio_de_ingreso_id integer,
    audio_para_contestadores_id integer,
    audios_id integer,
    campana_id integer,
    dial_timeout integer,
    destino_id integer,
    ivr_breakdown_id integer,
    announce_position boolean NOT NULL,
    wait_announce_frequency bigint,
    audio_previo_conexion_llamada_id integer,
    CONSTRAINT queue_table_pkey PRIMARY KEY (name),
    CONSTRAINT queue_table_campana_id_key UNIQUE (campana_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.reportes_app_actividadagentelog
(
    id serial NOT NULL,
    "time" timestamp with time zone NOT NULL,
    agente_id integer,
    event character varying(32) COLLATE pg_catalog."default",
    pausa_id character varying(128) COLLATE pg_catalog."default",
    CONSTRAINT reportes_app_actividadagentelog_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.reportes_app_llamadalog
(
    id serial NOT NULL,
    "time" timestamp with time zone NOT NULL,
    callid character varying(32) COLLATE pg_catalog."default",
    campana_id integer,
    tipo_campana integer,
    tipo_llamada integer,
    agente_id integer,
    event character varying(32) COLLATE pg_catalog."default",
    numero_marcado character varying(128) COLLATE pg_catalog."default",
    contacto_id integer,
    bridge_wait_time integer,
    duracion_llamada integer,
    archivo_grabacion character varying(100) COLLATE pg_catalog."default",
    agente_extra_id integer,
    campana_extra_id integer,
    numero_extra character varying(128) COLLATE pg_catalog."default",
    CONSTRAINT reportes_app_llamadalog_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.reportes_app_transferenciaaencuestalog
(
    id serial NOT NULL,
    "time" timestamp with time zone NOT NULL,
    agente_id integer,
    campana_id integer,
    encuesta_id integer,
    callid character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT reportes_app_transferenciaaencuestalog_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_ominicontacto_app_user_id FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authtoken_token_user_id_key
    ON public.authtoken_token(user_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_destinoentrante
    ADD CONSTRAINT configuracion_telefo_content_type_id_8f3d2b4d_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_content_type_id_8f3d2b4d
    ON public.configuracion_telefonia_app_destinoentrante(content_type_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_identificadorcliente
    ADD CONSTRAINT configuracion_telefo_audio_id_b57c0fee_fk_ominicont FOREIGN KEY (audio_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_audio_id_b57c0fee
    ON public.configuracion_telefonia_app_identificadorcliente(audio_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_ivr
    ADD CONSTRAINT configuracion_telefo_audio_principal_id_f765af13_fk_ominicont FOREIGN KEY (audio_principal_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_ivr_audio_principal_id_f765af13
    ON public.configuracion_telefonia_app_ivr(audio_principal_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_ivr
    ADD CONSTRAINT configuracion_telefo_invalid_audio_id_260b2a2a_fk_ominicont FOREIGN KEY (invalid_audio_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_ivr_invalid_audio_id_260b2a2a
    ON public.configuracion_telefonia_app_ivr(invalid_audio_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_ivr
    ADD CONSTRAINT configuracion_telefo_time_out_audio_id_e2235eb3_fk_ominicont FOREIGN KEY (time_out_audio_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_ivr_time_out_audio_id_e2235eb3
    ON public.configuracion_telefonia_app_ivr(time_out_audio_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_musicadeespera
    ADD CONSTRAINT configuracion_telefo_playlist_id_9fb0431b_fk_configura FOREIGN KEY (playlist_id)
    REFERENCES public.configuracion_telefonia_app_playlist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_musicadeespera_playlist_id_9fb0431b
    ON public.configuracion_telefonia_app_musicadeespera(playlist_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_opciondestino
    ADD CONSTRAINT configuracion_telefo_destino_anterior_id_0996ab3b_fk_configura FOREIGN KEY (destino_anterior_id)
    REFERENCES public.configuracion_telefonia_app_destinoentrante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_destino_anterior_id_0996ab3b
    ON public.configuracion_telefonia_app_opciondestino(destino_anterior_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_opciondestino
    ADD CONSTRAINT configuracion_telefo_destino_siguiente_id_5baf22fc_fk_configura FOREIGN KEY (destino_siguiente_id)
    REFERENCES public.configuracion_telefonia_app_destinoentrante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_destino_siguiente_id_5baf22fc
    ON public.configuracion_telefonia_app_opciondestino(destino_siguiente_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_ordentroncal
    ADD CONSTRAINT configuracion_telefo_ruta_saliente_id_bd46bea8_fk_configura FOREIGN KEY (ruta_saliente_id)
    REFERENCES public.configuracion_telefonia_app_rutasaliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_ruta_saliente_id_bd46bea8
    ON public.configuracion_telefonia_app_ordentroncal(ruta_saliente_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_ordentroncal
    ADD CONSTRAINT configuracion_telefo_troncal_id_edef8a14_fk_configura FOREIGN KEY (troncal_id)
    REFERENCES public.configuracion_telefonia_app_troncalsip (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_ordentroncal_troncal_id_edef8a14
    ON public.configuracion_telefonia_app_ordentroncal(troncal_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_patrondediscado
    ADD CONSTRAINT configuracion_telefo_ruta_saliente_id_7b111e0f_fk_configura FOREIGN KEY (ruta_saliente_id)
    REFERENCES public.configuracion_telefonia_app_rutasaliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_ruta_saliente_id_7b111e0f
    ON public.configuracion_telefonia_app_patrondediscado(ruta_saliente_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_rutaentrante
    ADD CONSTRAINT configuracion_telefo_destino_id_14fb9d9d_fk_configura FOREIGN KEY (destino_id)
    REFERENCES public.configuracion_telefonia_app_destinoentrante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_app_rutaentrante_destino_id_14fb9d9d
    ON public.configuracion_telefonia_app_rutaentrante(destino_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_validacionfechahora
    ADD CONSTRAINT configuracion_telefo_grupo_horario_id_2a6d57f1_fk_configura FOREIGN KEY (grupo_horario_id)
    REFERENCES public.configuracion_telefonia_app_grupohorario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_grupo_horario_id_2a6d57f1
    ON public.configuracion_telefonia_app_validacionfechahora(grupo_horario_id);


ALTER TABLE IF EXISTS public.configuracion_telefonia_app_validaciontiempo
    ADD CONSTRAINT configuracion_telefo_grupo_horario_id_d708e8ee_fk_configura FOREIGN KEY (grupo_horario_id)
    REFERENCES public.configuracion_telefonia_app_grupohorario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS configuracion_telefonia_ap_grupo_horario_id_d708e8ee
    ON public.configuracion_telefonia_app_validaciontiempo(grupo_horario_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_ominicontacto_app_user_id FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.form_app_gestion
    ADD CONSTRAINT form_app_gestion_agente_id_6cd04e65_fk_ominicont FOREIGN KEY (agente_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS form_app_gestion_agente_id_6cd04e65
    ON public.form_app_gestion(agente_id);


ALTER TABLE IF EXISTS public.form_app_gestion
    ADD CONSTRAINT form_app_gestion_campana_id_b19c7660_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS form_app_gestion_campana_id_b19c7660
    ON public.form_app_gestion(campana_id);


ALTER TABLE IF EXISTS public.form_app_gestion
    ADD CONSTRAINT form_app_gestion_ciudad_municipio_id_ba3675c8_fk_form_app_ FOREIGN KEY (ciudad_municipio_id)
    REFERENCES public.form_app_ciudadmunicipio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS form_app_gestion_ciudad_municipio_id_ba3675c8
    ON public.form_app_gestion(ciudad_municipio_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_actuacionvigente
    ADD CONSTRAINT ominicontacto_app_ac_campana_id_24d4b93b_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_actuacionvigente_campana_id_key
    ON public.ominicontacto_app_actuacionvigente(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agendacontacto
    ADD CONSTRAINT ominicontacto_app_ag_agente_id_34ccaf4a_fk_ominicont FOREIGN KEY (agente_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agendacontacto_agente_id_34ccaf4a
    ON public.ominicontacto_app_agendacontacto(agente_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agendacontacto
    ADD CONSTRAINT ominicontacto_app_ag_campana_id_364b62ec_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agendacontacto_campana_id_364b62ec
    ON public.ominicontacto_app_agendacontacto(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agendacontacto
    ADD CONSTRAINT ominicontacto_app_ag_contacto_id_81a823de_fk_ominicont FOREIGN KEY (contacto_id)
    REFERENCES public.ominicontacto_app_contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agendacontacto_contacto_id_81a823de
    ON public.ominicontacto_app_agendacontacto(contacto_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agenteensistemaexterno
    ADD CONSTRAINT ominicontacto_app_ag_agente_id_8a861404_fk_ominicont FOREIGN KEY (agente_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agenteensistemaexterno_agente_id_8a861404
    ON public.ominicontacto_app_agenteensistemaexterno(agente_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agenteensistemaexterno
    ADD CONSTRAINT ominicontacto_app_ag_sistema_externo_id_f6fba0d7_fk_ominicont FOREIGN KEY (sistema_externo_id)
    REFERENCES public.ominicontacto_app_sistemaexterno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agenteen_sistema_externo_id_f6fba0d7
    ON public.ominicontacto_app_agenteensistemaexterno(sistema_externo_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agenteprofile
    ADD CONSTRAINT ominicontacto_app_ag_grupo_id_474dfc5a_fk_ominicont FOREIGN KEY (grupo_id)
    REFERENCES public.ominicontacto_app_grupo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agenteprofile_grupo_id_474dfc5a
    ON public.ominicontacto_app_agenteprofile(grupo_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agenteprofile
    ADD CONSTRAINT ominicontacto_app_ag_reported_by_id_67c7fe30_fk_ominicont FOREIGN KEY (reported_by_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agenteprofile_reported_by_id_67c7fe30
    ON public.ominicontacto_app_agenteprofile(reported_by_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_agenteprofile
    ADD CONSTRAINT ominicontacto_app_ag_user_id_0e446b03_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_agenteprofile_user_id_key
    ON public.ominicontacto_app_agenteprofile(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_auditoriacalificacion
    ADD CONSTRAINT ominicontacto_app_au_calificacion_id_dd3d39f1_fk_ominicont FOREIGN KEY (calificacion_id)
    REFERENCES public.ominicontacto_app_calificacioncliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_auditoriacalificacion_calificacion_id_key
    ON public.ominicontacto_app_auditoriacalificacion(calificacion_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_calificacioncliente
    ADD CONSTRAINT ominicontacto_app_ca_agente_id_1070b434_fk_ominicont FOREIGN KEY (agente_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_calificacioncliente_agente_id_1070b434
    ON public.ominicontacto_app_calificacioncliente(agente_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_calificacioncliente
    ADD CONSTRAINT ominicontacto_app_ca_contacto_id_e5df4663_fk_ominicont FOREIGN KEY (contacto_id)
    REFERENCES public.ominicontacto_app_contacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_calificacioncliente_contacto_id_e5df4663
    ON public.ominicontacto_app_calificacioncliente(contacto_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_calificacioncliente
    ADD CONSTRAINT ominicontacto_app_ca_opcion_calificacion__5ad7e22c_fk_ominicont FOREIGN KEY (opcion_calificacion_id)
    REFERENCES public.ominicontacto_app_opcioncalificacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_califica_opcion_calificacion_id_5ad7e22c
    ON public.ominicontacto_app_calificacioncliente(opcion_calificacion_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana
    ADD CONSTRAINT ominicontacto_app_ca_bd_contacto_id_3b5858cd_fk_ominicont FOREIGN KEY (bd_contacto_id)
    REFERENCES public.ominicontacto_app_basedatoscontacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_bd_contacto_id_3b5858cd
    ON public.ominicontacto_app_campana(bd_contacto_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana
    ADD CONSTRAINT ominicontacto_app_ca_outr_id_2cd2dd43_fk_configura FOREIGN KEY (outr_id)
    REFERENCES public.configuracion_telefonia_app_rutasaliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_outr_id_2cd2dd43
    ON public.ominicontacto_app_campana(outr_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana
    ADD CONSTRAINT ominicontacto_app_ca_reported_by_id_cb70293d_fk_ominicont FOREIGN KEY (reported_by_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_reported_by_id_cb70293d
    ON public.ominicontacto_app_campana(reported_by_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana
    ADD CONSTRAINT ominicontacto_app_ca_sistema_externo_id_6654b990_fk_ominicont FOREIGN KEY (sistema_externo_id)
    REFERENCES public.ominicontacto_app_sistemaexterno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_sistema_externo_id_6654b990
    ON public.ominicontacto_app_campana(sistema_externo_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana
    ADD CONSTRAINT ominicontacto_app_ca_sitio_externo_id_e255b47e_fk_ominicont FOREIGN KEY (sitio_externo_id)
    REFERENCES public.ominicontacto_app_sitioexterno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_sitio_externo_id_e255b47e
    ON public.ominicontacto_app_campana(sitio_externo_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana_supervisors
    ADD CONSTRAINT ominicontacto_app_ca_campana_id_242d5c1e_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_supervisors_campana_id_242d5c1e
    ON public.ominicontacto_app_campana_supervisors(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_campana_supervisors
    ADD CONSTRAINT ominicontacto_app_ca_user_id_7aafcfff_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_campana_supervisors_user_id_7aafcfff
    ON public.ominicontacto_app_campana_supervisors(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_chat
    ADD CONSTRAINT ominicontacto_app_ch_agente_id_b0b74e82_fk_ominicont FOREIGN KEY (agente_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_chat_agente_id_b0b74e82
    ON public.ominicontacto_app_chat(agente_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_chat
    ADD CONSTRAINT ominicontacto_app_ch_user_id_7e593d05_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_chat_user_id_7e593d05
    ON public.ominicontacto_app_chat(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_clientewebphoneprofile
    ADD CONSTRAINT ominicontacto_app_cl_user_id_bbe551e4_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_clientewebphoneprofile_user_id_key
    ON public.ominicontacto_app_clientewebphoneprofile(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_configuraciondeagentesdecampana
    ADD CONSTRAINT ominicontacto_app_co_campana_id_cf9a53c6_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_configuraciondeagentesdecampan_campana_id_key
    ON public.ominicontacto_app_configuraciondeagentesdecampana(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_configuraciondepausa
    ADD CONSTRAINT ominicontacto_app_co_conjunto_de_pausa_id_87162770_fk_ominicont FOREIGN KEY (conjunto_de_pausa_id)
    REFERENCES public.ominicontacto_app_conjuntodepausa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_configur_conjunto_de_pausa_id_87162770
    ON public.ominicontacto_app_configuraciondepausa(conjunto_de_pausa_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_configuraciondepausa
    ADD CONSTRAINT ominicontacto_app_co_pausa_id_762e4a99_fk_ominicont FOREIGN KEY (pausa_id)
    REFERENCES public.ominicontacto_app_pausa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_configuraciondepausa_pausa_id_762e4a99
    ON public.ominicontacto_app_configuraciondepausa(pausa_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_contacto
    ADD CONSTRAINT ominicontacto_app_co_bd_contacto_id_e36d02df_fk_ominicont FOREIGN KEY (bd_contacto_id)
    REFERENCES public.ominicontacto_app_basedatoscontacto (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_contacto_bd_contacto_id_e36d02df
    ON public.ominicontacto_app_contacto(bd_contacto_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_contactoblacklist
    ADD CONSTRAINT ominicontacto_app_co_black_list_id_718e9765_fk_ominicont FOREIGN KEY (black_list_id)
    REFERENCES public.ominicontacto_app_blacklist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_contactoblacklist_black_list_id_718e9765
    ON public.ominicontacto_app_contactoblacklist(black_list_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_contactolistarapida
    ADD CONSTRAINT ominicontacto_app_co_lista_rapida_id_60bb61c9_fk_ominicont FOREIGN KEY (lista_rapida_id)
    REFERENCES public.ominicontacto_app_listasrapidas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_contactolistarapida_lista_rapida_id_60bb61c9
    ON public.ominicontacto_app_contactolistarapida(lista_rapida_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_fieldformulario
    ADD CONSTRAINT ominicontacto_app_fi_formulario_id_b5355e5d_fk_ominicont FOREIGN KEY (formulario_id)
    REFERENCES public.ominicontacto_app_formulario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_fieldformulario_formulario_id_b5355e5d
    ON public.ominicontacto_app_fieldformulario(formulario_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_grupo
    ADD CONSTRAINT ominicontacto_app_gr_conjunto_de_pausa_id_8d3e5455_fk_ominicont FOREIGN KEY (conjunto_de_pausa_id)
    REFERENCES public.ominicontacto_app_conjuntodepausa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_grupo_conjunto_de_pausa_id_8d3e5455
    ON public.ominicontacto_app_grupo(conjunto_de_pausa_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_historicalcalificacioncliente
    ADD CONSTRAINT ominicontacto_app_hi_history_user_id_51068f0a_fk_ominicont FOREIGN KEY (history_user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_historic_history_user_id_51068f0a
    ON public.ominicontacto_app_historicalcalificacioncliente(history_user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_historicalrespuestaformulariogestion
    ADD CONSTRAINT ominicontacto_app_hi_history_user_id_2f174ef7_fk_ominicont FOREIGN KEY (history_user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_historic_history_user_id_2f174ef7
    ON public.ominicontacto_app_historicalrespuestaformulariogestion(history_user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_mensajechat
    ADD CONSTRAINT ominicontacto_app_me_chat_id_3845da5b_fk_ominicont FOREIGN KEY (chat_id)
    REFERENCES public.ominicontacto_app_chat (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_mensajechat_chat_id_3845da5b
    ON public.ominicontacto_app_mensajechat(chat_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_mensajechat
    ADD CONSTRAINT ominicontacto_app_me_sender_id_49a6c90d_fk_ominicont FOREIGN KEY (sender_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_mensajechat_sender_id_49a6c90d
    ON public.ominicontacto_app_mensajechat(sender_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_mensajechat
    ADD CONSTRAINT ominicontacto_app_me_to_id_a5f7aa2c_fk_ominicont FOREIGN KEY (to_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_mensajechat_to_id_a5f7aa2c
    ON public.ominicontacto_app_mensajechat(to_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_opcioncalificacion
    ADD CONSTRAINT ominicontacto_app_op_campana_id_8feac367_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_opcioncalificacion_campana_id_8feac367
    ON public.ominicontacto_app_opcioncalificacion(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_opcioncalificacion
    ADD CONSTRAINT ominicontacto_app_op_formulario_id_a0906f50_fk_ominicont FOREIGN KEY (formulario_id)
    REFERENCES public.ominicontacto_app_formulario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_opcioncalificacion_formulario_id_a0906f50
    ON public.ominicontacto_app_opcioncalificacion(formulario_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_parametroscrm
    ADD CONSTRAINT ominicontacto_app_pa_campana_id_c8dd4478_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_parametroscrm_campana_id_c8dd4478
    ON public.ominicontacto_app_parametroscrm(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_reglaincidenciaporcalificacion
    ADD CONSTRAINT ominicontacto_app_re_opcion_calificacion__ac76a6d5_fk_ominicont FOREIGN KEY (opcion_calificacion_id)
    REFERENCES public.ominicontacto_app_opcioncalificacion (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_reglaincidenciapor_opcion_calificacion_id_key
    ON public.ominicontacto_app_reglaincidenciaporcalificacion(opcion_calificacion_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_reglasincidencia
    ADD CONSTRAINT ominicontacto_app_re_campana_id_707899e9_fk_ominicont FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_reglasincidencia_campana_id_707899e9
    ON public.ominicontacto_app_reglasincidencia(campana_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_respuestaformulariogestion
    ADD CONSTRAINT ominicontacto_app_re_calificacion_id_c0a65d38_fk_ominicont FOREIGN KEY (calificacion_id)
    REFERENCES public.ominicontacto_app_calificacioncliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_respuest_calificacion_id_c0a65d38
    ON public.ominicontacto_app_respuestaformulariogestion(calificacion_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_sitioexterno
    ADD CONSTRAINT ominicontacto_app_si_autenticacion_id_659d1062_fk_ominicont FOREIGN KEY (autenticacion_id)
    REFERENCES public.ominicontacto_app_autenticacionsitioexterno (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_sitioexterno_autenticacion_id_659d1062
    ON public.ominicontacto_app_sitioexterno(autenticacion_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_supervisorprofile
    ADD CONSTRAINT ominicontacto_app_su_user_id_e8fa6d81_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_supervisorprofile_user_id_key
    ON public.ominicontacto_app_supervisorprofile(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_user_groups
    ADD CONSTRAINT ominicontacto_app_us_group_id_f47e61a0_fk_auth_grou FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_user_groups_group_id_f47e61a0
    ON public.ominicontacto_app_user_groups(group_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_user_groups
    ADD CONSTRAINT ominicontacto_app_us_user_id_9520c89f_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_user_groups_user_id_9520c89f
    ON public.ominicontacto_app_user_groups(user_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_user_user_permissions
    ADD CONSTRAINT ominicontacto_app_us_permission_id_43f9ab68_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_user_user_permissions_permission_id_43f9ab68
    ON public.ominicontacto_app_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.ominicontacto_app_user_user_permissions
    ADD CONSTRAINT ominicontacto_app_us_user_id_4412e21b_fk_ominicont FOREIGN KEY (user_id)
    REFERENCES public.ominicontacto_app_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS ominicontacto_app_user_user_permissions_user_id_4412e21b
    ON public.ominicontacto_app_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.queue_member_table
    ADD CONSTRAINT queue_member_table_member_id_0e6c0aa5_fk_ominicont FOREIGN KEY (member_id)
    REFERENCES public.ominicontacto_app_agenteprofile (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_member_table_member_id_0e6c0aa5
    ON public.queue_member_table(member_id);


ALTER TABLE IF EXISTS public.queue_member_table
    ADD CONSTRAINT queue_member_table_queue_name_cc6b888a_fk_queue_table_name FOREIGN KEY (queue_name)
    REFERENCES public.queue_table (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_member_table_queue_name_cc6b888a
    ON public.queue_member_table(queue_name);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_audio_de_ingreso_id_28e2a56e_fk_ominicont FOREIGN KEY (audio_de_ingreso_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_audio_de_ingreso_id_28e2a56e
    ON public.queue_table(audio_de_ingreso_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_audio_para_contestad_49e13f02_fk_ominicont FOREIGN KEY (audio_para_contestadores_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_audio_para_contestadores_id_49e13f02
    ON public.queue_table(audio_para_contestadores_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_audio_previo_conexio_5034bc70_fk_ominicont FOREIGN KEY (audio_previo_conexion_llamada_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_audio_previo_conexion_llamada_id_5034bc70
    ON public.queue_table(audio_previo_conexion_llamada_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_audios_id_e9679a0c_fk_ominicont FOREIGN KEY (audios_id)
    REFERENCES public.ominicontacto_app_archivodeaudio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_audios_id_e9679a0c
    ON public.queue_table(audios_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_campana_id_be72b1c4_fk_ominicontacto_app_campana_id FOREIGN KEY (campana_id)
    REFERENCES public.ominicontacto_app_campana (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_campana_id_key
    ON public.queue_table(campana_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_destino_id_3b1b009f_fk_configura FOREIGN KEY (destino_id)
    REFERENCES public.configuracion_telefonia_app_destinoentrante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_destino_id_3b1b009f
    ON public.queue_table(destino_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_ivr_breakdown_id_9d6d0bcd_fk_configura FOREIGN KEY (ivr_breakdown_id)
    REFERENCES public.configuracion_telefonia_app_destinoentrante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_ivr_breakdown_id_9d6d0bcd
    ON public.queue_table(ivr_breakdown_id);


ALTER TABLE IF EXISTS public.queue_table
    ADD CONSTRAINT queue_table_musiconhold_id_207bcb8a_fk_configura FOREIGN KEY (musiconhold_id)
    REFERENCES public.configuracion_telefonia_app_playlist (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS queue_table_musiconhold_id_207bcb8a
    ON public.queue_table(musiconhold_id);

END;